services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sct-user
      MYSQL_PASSWORD: insecure_password
      MYSQL_DATABASE: sct_system_db
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$sct-user --password=$$insecure_password
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
#    volumes:
#      - /c/Users/chiku/dev/data/volumes/sct-system:/var/lib/mysql
  backend:
    build:
      context: ./sct-system/
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_USER=sct-user
      - DB_PASSWORD=insecure_password
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=sct_system_db
    depends_on:
      mysql:
        condition: service_healthy
  ui:
    build:
      context: ./ui/
      dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - backend